server:
  port: 9082


spring:
  application:
    name: consul-comsumer-payment
  cloud:
    consul:
      host: 192.168.1.110
      port: 8500
      discovery:
        service-name: ${spring.application.name}