server:
  port: 8004


spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: 192.168.1.110
      port: 8500
      discovery:
        service-name: ${spring.application.name}